# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4865687e8988056d1a85d416b9f617513dc8f50e5f2bbfdd691dea9fd8e505059acc34d8750d44077a78dfb83ae633faaa36b67d714028cafe0c312aca632c

test:
  secret_key_base: e9103320725a12ef4d25c44e4e4cce8f7850aa264d6041d41c33c84c52d08c558411e2ffd19065c38a5346a699eb209235052f4a01860289f07c77c49fae9f22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
